### ISSUE TITLE
Images to pdf

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#10]
Add functionality to convert img to pdf

**Comment by Korra15** [comment]
Could I work on this using python?

**Comment by leesha19** [comment]
> Add functionality to convert img to pdf

i can do it using js please assign me

**Comment by shivshankar9** [comment]
> Could I work on this using python?

Ok

**Comment by srinivasulu-2654** [comment]
I can do this task . please assign this task for me

**Comment by shivshankar9** [comment]
> I can do this task . please assign this task for me

This issue already assigned
