### ISSUE TITLE
Doc-to-Pdf page UI improvement

### ISSUE THREAD

**Issue by udith51** [shivshankar9/Student-portal#105]
Though the functionality of doc-to-pdf conversion has been worked out, ui of of this page is yet to be improved to sync it with main page theme

**Comment by udith51** [comment]
@shivshankar9, please assign it to me.

**Comment by udith51** [comment]
@shivshankar9 do we have a prototype of design (as in images on how it should look or some guidelines maybe) ready that can be implemented here?

**Comment by udith51** [comment]
Or do we need to start from a complete new idea?

**Comment by shivshankar9** [comment]
> Or do we need to start from a complete new idea?

no there is no prototype
make sure it similiar to theme page

**Comment by udith51** [comment]
@shivshankar9 you may review #114 now!!
