### ISSUE TITLE
Text to pdf

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#11]
Functionality text text to pdf

**Comment by davyj123** [comment]
could you please assign this issue to me. I am already working on it.

**Comment by shivshankar9** [comment]
> could you please assign this issue to me. I am already working on it.

Yeah sure

**Comment by udith51** [comment]
Hey, @shivshankar9 if this issue thread is inactive, can I work on it?

**Comment by davyj123** [comment]
@shivshankar9 sir I am busy with my exams but now will send a pr in some days

**Comment by shivshankar9** [comment]
> @shivshankar9 sir I am busy with my exams but now will send a pr in some days

Ok no worries take your time.

**Comment by udith51** [comment]
Ok, no problem @davyj123 🙂👍

**Comment by davyj123** [comment]
@shivshankar9  sir i sent pr #124 please check it.
