### ISSUE TITLE
add preloader 

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#111]

**Comment by KashyapB02** [comment]
@shivshankar9 

Can you please provide some description of the issue? I am not able to understand what exactly I have to do about this issue. So adding a preview or some guidelines will be very much helpful for me.

I am a SWOC contributor.

**Comment by aakankshabhende** [comment]
@kashyap1905 you will have to create something which will be shown on the screen till the main content of website is loaded

**Comment by abaran803** [comment]
@shivshankar9  @aakankshabhende 
Are you talking about the loader I used in [this](https://abaran803.github.io/E-Commerce/#/home) project to load the product and category section?
If it is the same, please assign this issue to me, as I can do it easily.

**Comment by abaran803** [comment]
Do I need to do something more on this issue?
