### ISSUE TITLE
add logo to title 

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#112]

**Comment by abaran803** [comment]
Please assign this issue to me
I will add relevant a logo before the title.

**Comment by abaran803** [comment]
@shivshankar9 I think, someone already added the logo before the title using #110 issue, can I add the logo before all the navs, related to their name.

**Comment by shivshankar9** [comment]
> @shivshankar9 I think, someone already added the logo before the title using #110 issue, can I add the logo before all the navs, related to their name.

Actually This issue for page title not for nav

**Comment by abaran803** [comment]
> > @shivshankar9 I think, someone already added the logo before the title using #110 issue, can I add the logo before all the navs, related to their name.
> 
> Actually This issue for page title not for nav

So what should I do?

**Comment by shivshankar9** [comment]
> > > @shivshankar9 I think, someone already added the logo before the title using #110 issue, can I add the logo before all the navs, related to their name.
> > 
> > 
> > Actually This issue for page title not for nav
> 
> So what should I do?

Add logo to page title

**Comment by abaran803** [comment]
> > > > @shivshankar9 I think, someone already added the logo before the title using #110 issue, can I add the logo before all the navs, related to their name.
> > > 
> > > 
> > > Actually This issue for page title not for nav
> > 
> > 
> > So what should I do?
> 
> Add logo to page title

Ok, I'll do it

**Comment by abaran803** [comment]
> > > > > @shivshankar9 I think, someone already added the logo before the title using #110 issue, can I add the logo before all the navs, related to their name.
> > > > 
> > > > 
> > > > Actually This issue for page title not for nav
> > > 
> > > 
> > > So what should I do?
> > 
> > 
> > Add logo to page title
> 
> Ok, I'll do it
Should I add the same logo used on the page?
