### ISSUE TITLE
Doc To Pdf

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#12]
Doc to pdf converter

**Comment by davyj123** [comment]
could you please assign this issue to me

**Comment by shivshankar9** [comment]
> could you please assign this issue to me

Yeah sure

**Comment by shivshankar9** [comment]
> could you please assign this issue to me

@davyj123

**Comment by davyj123** [comment]
Sending a pr soon

**Comment by davyj123** [comment]
Almost finished

**Comment by udith51** [comment]
@shivshankar9, just bringing it to your notice, this issue already exists (#7) and its pr has been successfully merged(#84).
Thanks!
