### ISSUE TITLE
Extract Zip file UI

### ISSUE THREAD

**Issue by udith51** [shivshankar9/Student-portal#123]
At present, on clicking **Extract zip file** button, it links to nowhere. This issue would get us a landing page where the **Extract zip** functionality can be carried out.

**Comment by udith51** [comment]
Please assign it to me!

**Comment by udith51** [comment]
Hey @udith51, could you please add relevant tags to the newer issues :)

**Comment by swati2603** [comment]
@udith51 Are you working on it or should I assign it to someone else?

**Comment by udith51** [comment]
@swati2603, actually I was waiting for #13 to be merged. Ones the functionality is done, I could go forward with UI, else doing UI first and then going with functionality might create a lot of bugs by the end. So I worked on Img-to-Pdf UI (which got merged today) and ones #13 gets merged, I can work on this. Still if you want, I can start working on this pr now.

**Comment by swati2603** [comment]
> @swati2603, actually I was waiting for #13 to be merged. Ones the functionality is done, I could go forward with UI, else doing UI first and then going with functionality might create a lot of bugs by the end. So I worked on Img-to-Pdf UI (which got merged today) and ones #13 gets merged, I can work on this. Still if you want, I can start working on this pr now.

Okay, no problem.

**Comment by udith51** [comment]
@shivshankar9, do we need these extra customizations?

![image](https://user-images.githubusercontent.com/72927422/150801314-ce825ec1-3623-4dd1-bb69-1040bd323906.png)

I feel this is a general website for students and while extracting zip file, they don't need this. What do you say?
