### ISSUE TITLE
Changes in contact us page 

### ISSUE THREAD

**Issue by geetika005** [shivshankar9/Student-portal#126]
The colours of contact us page do not match with the theme of the website ,i want to change the colours of the page.

**Comment by geetika005** [comment]
please assign the issue to me

**Comment by swati2603** [comment]
> please assign the issue to me
Right now **Submit** button is not working. After submission, a message should pop up in which it is written that _Thank you, we will respond to you soon._  Can you fix it?

**Comment by geetika005** [comment]
> > please assign the issue to me
> > Right now **Submit** button is not working. After submission, a message should pop up in which it is written that _Thank you, we will respond to you soon._  Can you fix it?

Yes i will fix that too
