### ISSUE TITLE
Extract zip file

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#13]
Function to extract zip files

**Comment by santushtisharma10** [comment]
@shivshankar9  I would like to work on this issue. Please assign me this issue

**Comment by santushtisharma10** [comment]
@shivshankar9

**Comment by shivshankar9** [comment]
> @shivshankar9 I would like to work on this issue. Please assign me this issue

Yes sure go ahead

**Comment by ARUNBALACHOCKALINGAM** [comment]
Please assign me this issue

**Comment by aakankshabhende** [comment]
Any updates? @ARUNBALACHOCKALINGAM

**Comment by ARUNBALACHOCKALINGAM** [comment]
> Any updates? @ARUNBALACHOCKALINGAM

I'll try to make a PR by EOD

**Comment by aakankshabhende** [comment]
Okay no issues @ARUNBALACHOCKALINGAM
