### ISSUE TITLE
Text-to-Pdf link is not working Fix it

### ISSUE THREAD

**Issue by Abirpal202049** [shivshankar9/Student-portal#141]

**Comment by rishitajain01** [comment]
please assign this to me..

**Comment by rishitajain01** [comment]
but it is working..

**Comment by Abirpal202049** [comment]
> but it is working..

No its not working its showing 404 error. If you want to work tell us

**Comment by rishitajain01** [comment]
@Abirpal202049 I want to work on it. Please assign it to me

**Comment by udith51** [comment]
Hey @Abirpal202049 @aakankshabhende , can I work on this?

**Comment by siva-krish45** [comment]
hey @Abirpal202049 @aakankshabhende i am new to open source... will you please assign it to me ? i already worked on it so that it will be my first meaningful pull request.
