### ISSUE TITLE
Services button is not working

### ISSUE THREAD

**Issue by TMahato** [shivshankar9/Student-portal#150]
I would like to fix this issue. 
Please assign me this.

**Comment by swati2603** [comment]
> I would like to fix this issue. Please assign me this.

What changes would you make in that section?

**Comment by TMahato** [comment]
Like the service button is not working so I will redirect to the tool section when it is clicked.

**Comment by TMahato** [comment]
I am not able to find nav links, it's not in index.html, in which file it is in?
