### ISSUE TITLE
user defined filename in the text to pdf tool

### ISSUE THREAD

**Issue by siva-krish45** [shivshankar9/Student-portal#156]
**Is your feature request related to a problem? Please describe.**

whenever we download the pdf in the text to pdf feature , the filename remains the same (text.pdf)

**Describe the solution you'd like**

the tool should have a input field for getting the user defined filename. whenever it is downloaded the pdf should be like
( user defined filename.pdf)

if the input is syllabus , then the output of the pdf should be **(syllabus.pdf)**

**Comment by siva-krish45** [comment]
can i work on it ?

**Comment by swati2603** [comment]
> can i work on it ?

Yes
