### ISSUE TITLE
Change Resize image service page UI design.

### ISSUE THREAD

**Issue by devikavarshney** [shivshankar9/Student-portal#167]
**Is your feature request related to a problem? Please describe.**
The UI design of the resize image service is not consistent with the design of the website.

**Describe the solution you'd like**
I will completely change the design of the Resize service page.

**Comment by devikavarshney** [comment]
@shivshankar9 @aakankshabhende please assign this issue to me.

**Comment by aakankshabhende** [comment]
Go for it @devikavarshney

**Comment by devikavarshney** [comment]
@shivshankar9 Please add tags to this issue.

**Comment by devikavarshney** [comment]
@shivshankar9 @aakankshabhende Please check PR #177.
