### ISSUE TITLE
The Services button on nav bar is not working accurately

### ISSUE THREAD

**Issue by abhinav2712** [shivshankar9/Student-portal#168]
I was going through the website and found that when pressing service button on nav bar, it redirects me exactly at same place which home button directs to.

I would like to fi the code for directing it to correct container which is "tools"

**Additional context**
Also if possible, consider changing whole UI design because the website looks too "big" or zoomed in if you know what I mean

**Comment by devikavarshney** [comment]
@abhinav2712 Hey, I have already solved this issue and sent the PR.

**Comment by abhinav2712** [comment]
> @abhinav2712 Hey, I have already solved this issue and sent the PR.

Ohh ohkay, I am kinda newbie here so i didnt  check PR's...

**Comment by aakankshabhende** [comment]
@abhinav2712 you can check other issues or create your own relevant issues :)

**Comment by aakankshabhende** [comment]
@abhinav2712 you can check issue #155

**Comment by abhinav2712** [comment]
> @abhinav2712 you can check issue #155 

Yeah surely i would do
