### ISSUE TITLE
Change the design of image to pdf and doc to pdf page for light mode

### ISSUE THREAD

**Issue by devikavarshney** [shivshankar9/Student-portal#189]
**Is your feature request related to a problem? Please describe.**
The toggle button is not working for our services that are image to pdf and doc to pdf page.

**Describe the solution you'd like**
I will change the design of the image to pdf and doc to pdf page for light mode.

**Comment by devikavarshney** [comment]
@shivshankar9 @aakankshabhende @swati2603 Please assign this issue to me and check PR #188.

**Comment by swati2603** [comment]
We have assigned someone else. Please check previous issues.

**Comment by devikavarshney** [comment]
@swati2603 hey actually I didn't see that issue and after sending PR I checked. I am sorry for that. But you can merge for img and doc page if that is okay for you and the person you assigned first can do for the rest.

**Comment by swati2603** [comment]
> @swati2603 hey actually I didn't see that issue and after sending PR I checked. I am sorry for that. But you can merge for img and doc page if that is okay for you and the person you assigned first can do for the rest.

It's alright. You may start working on other issues.

**Comment by devikavarshney** [comment]
@swati2603 Hey then why did you accept the mail button PR of someone else I think it was assigned to me first.

**Comment by swati2603** [comment]
> @swati2603 Hey then why did you accept the mail button PR of someone else I think it was assigned to me first.

Dear, I have already merged that PR. And for the same issue, If there will be two PR then Conflicts will come. I told you on discord too. Please check.
