### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#23]
Create logo and add to homepage

**Comment by geetika005** [comment]
Please assign the issue to me.

**Comment by shivshankar9** [comment]
> Please assign the issue to me.

Yeah sure go ahead

**Comment by shivshankar9** [comment]
@geetika005  any updates??

**Comment by 9Shalini** [comment]
![logo](https://user-images.githubusercontent.com/87543203/145801674-e8d6ea07-debb-44d8-9212-1a805c6d7f43.png)
I can redesign the logo, please assign me the task @shivshankar9

**Comment by shivshankar9** [comment]
> ![logo](https://user-images.githubusercontent.com/87543203/145801674-e8d6ea07-debb-44d8-9212-1a805c6d7f43.png) I can redesign the logo, please assign me the task @shivshankar9

Ok go ahead
