### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#3]

**Comment by radzhiv25** [comment]
can you please assign this to me

**Comment by shivshankar9** [comment]
> can you please assign this to me

Yes sure

**Comment by Viditjain04** [comment]
@shivshankar9 I have updated the Readme file and made a pr #6 also, please review and accept it.

**Comment by radzhiv25** [comment]
> > can you please assign this to me
> 
> 
> 
> Yes sure

So still can I create a PR ?

**Comment by shivshankar9** [comment]
> > > can you please assign this to me
> > 
> > 
> > Yes sure
> 
> So still can I create a PR ?

If you think there is something needed update create new issue and I will assign to you
