### ISSUE TITLE
Tools Section

### ISSUE THREAD

**Issue by TMahato** [shivshankar9/Student-portal#34]
I think I can improve the design of the Tool Section.

![tools](https://user-images.githubusercontent.com/80240317/145524222-1edf6a35-9b0c-4bb6-83ca-b8378edbde72.png)

**Comment by shivshankar9** [comment]
> I think I can improve the design of the Tool Section.
> 
> ![tools](https://user-images.githubusercontent.com/80240317/145524222-1edf6a35-9b0c-4bb6-83ca-b8378edbde72.png)

Go ahead

**Comment by tiasaxena** [comment]
![toolsec](https://user-images.githubusercontent.com/89907755/145789344-b11590be-31d3-4fed-b1ea-19bb135ad20b.png)

Hey @shivshankar9! I can work on improving the tool section further. Can I please be assigned the task?

**Comment by shivshankar9** [comment]
> ![toolsec](https://user-images.githubusercontent.com/89907755/145789344-b11590be-31d3-4fed-b1ea-19bb135ad20b.png)
> 
> Hey @shivshankar9! I can work on improving the tool section further. Can I please be assigned the task?

Go ahead

**Comment by TMahato** [comment]
I am already working on it
almost completed
??
