### ISSUE TITLE
Textutility page

### ISSUE THREAD

**Issue by Dipti821** [shivshankar9/Student-portal#35]
I would like to add a page where we can perform different operations on text like converting text to upper case and lower case, counting no. of words and characters, copying the text etc.

**Comment by Dipti821** [comment]
Hey @shivshankar9 I would like to work on this issue. Can I?

**Comment by shivshankar9** [comment]
> Hey @shivshankar9 I would like to work on this issue. Can I?

Sure

**Comment by Pushti-R** [comment]
Can i work on it?

**Comment by shivshankar9** [comment]
> Can i work on it?

 Since there is no updates from Dipti you can start working,

**Comment by shivshankar9** [comment]
> > Can i work on it?
> 
> Since there is no updates from Dipti!!!
 you can start working,

**Comment by Pushti-R** [comment]
hey @shivshankar9  can you brief me a little about this task?

**Comment by shivshankar9** [comment]
> hey @shivshankar9 can you brief me a little about this task?

Actually this issue created by Dipti, 
You can work on the other issue if u not getting ,
if u wish to work on function or ui related just create another Issue.
