### ISSUE TITLE
Chatbot for Homepage

### ISSUE THREAD

**Issue by NamanGokharu** [shivshankar9/Student-portal#37]
I am thinking to go on with chatbot for homepage using JS, HTML  & CSS which will help to resolve basic issues faced by user.

**Comment by shivshankar9** [comment]
> I am thinking to go on with chatbot for homepage using JS, HTML & CSS which will help to resolve basic issues faced by user.

Go ahead

**Comment by shivshankar9** [comment]
> I am thinking to go on with chatbot for homepage using JS, HTML & CSS which will help to resolve basic issues faced by user.

Any updates @NamanGokharu

**Comment by NamanGokharu** [comment]
Going on with some basic errors, I will complete it and submit it by today.

**Comment by shivshankar9** [comment]
> Going on with some basic errors, I will complete it and submit it by today.

Take your time, if you face any issues you can ask to mentors
