### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#4]

**Comment by ssurbhi09** [comment]
Like what I have to do?

**Comment by shivshankar9** [comment]
> Like what I have to do?

https://smallpdf.com/
Checkout this create some simple home page
Include, blog, details about features,

**Comment by davyj123** [comment]
is this repo is part of swoc 2021.
i am intrested to do this task.
can you give some psd or figma designs.

**Comment by madhuri878** [comment]
I am also interested to contribute this repo can you give more brief idea what exactly i can add.

**Comment by shivshankar9** [comment]
> is this repo is part of swoc 2021. i am intrested to do this task. can you give some psd or figma designs.

Well we starting this project from begging so design this in your way,

**Comment by shivshankar9** [comment]
> I am also interested to contribute this repo can you give more brief idea what exactly i can add.

You can visit smallpdf.com get some idea 
We creating those all smart features that students needs to customize files

**Comment by srinivasulu-2654** [comment]
I am intrested in  doing this task by adding more . Please assign this task to me

**Comment by shivshankar9** [comment]
> I am intrested in doing this task by adding more . Please assign this task to me

Yes sure ,

**Comment by leesha19** [comment]
> > I am intrested in doing this task by adding more . Please assign this task to me
> 
> Yes sure ,

hey i am also intrested in this project can you please give some home page content i can write all structure in html if you provide me

**Comment by shivshankar9** [comment]
> > > I am intrested in doing this task by adding more . Please assign this task to me
> > 
> > 
> > Yes sure ,
> 
> hey i am also intrested in this project can you please give some home page content i can write all structure in html if you provide me

Well there is no content available
Explore internet you will find some content

**Comment by HarivardhanK** [comment]
please assign me this issue. I'm interested. I can do it

**Comment by shivshankar9** [comment]
> please assign me this issue. I'm interested. I can do it

Yes go ahead,
But only first PR will get merged

**Comment by shivshankar9** [comment]
@kanthalaHarivardhanReddy @ssurbhi09  @leesha19 @madhuri878 
Guys only First PR will get merged,
So complete it asap..

**Comment by leesha19** [comment]
> @kanthalaHarivardhanReddy @ssurbhi09 @leesha19 @madhuri878 Guys only First PR will get merged, So complete it asap..

done

**Comment by leesha19** [comment]
#15
