### ISSUE TITLE
Change width of heading

### ISSUE THREAD

**Issue by abaran803** [shivshankar9/Student-portal#42]
I would like to apply the width of the main heading "student portal" according to the size of screen, instead of a fixed size.

![temp1](https://user-images.githubusercontent.com/71405368/145698998-ec48b208-1143-465f-8b8d-50af15e0404c.png)
On large screen

<img src="https://user-images.githubusercontent.com/71405368/145699043-2f6dc29d-bff6-4f0f-99be-6e028af09b10.png" width=50% height=50%>
On the small screen, before changes
<br><br><br>
<img src="https://user-images.githubusercontent.com/71405368/145699050-688d98a4-9aef-47a2-bc52-3cbaca9af40f.png" width=50% height=50%>
On the small screen, after changes

**Comment by ghost** [comment]
Please assign the issue to me.

**Comment by abaran803** [comment]
It was the problem with the navbar. And now working fine. But on applying centre alignment, the header will look better in small screen devices. Also, the navbar is not responsive on all devices due to applying media query for 400px screen, it will work for all devices if we set it to 480px. I'm want to do these two changes.
