### ISSUE TITLE
Adding image to pdf page

### ISSUE THREAD

**Issue by abaran803** [shivshankar9/Student-portal#47]
I want to add the front-end part of the "image to pdf" section. Initially, one form is given to provide input of the image. And if the user wants to add more images, he can click on add more button. If the user wants to get the pdf format of all the images, he will click on the upload all button.

![temp](https://user-images.githubusercontent.com/71405368/145714608-7bb30109-c6ac-4c29-8968-a4412307ffd5.png)
Design of the front-end part

**Comment by shivshankar9** [comment]
> I want to add the front-end part of the "image to pdf" section. Initially, one form is given to provide input of the image. And if the user wants to add more images, he can click on add more button. If the user wants to get the pdf format of all the images, he will click on the upload all button.
> 
> ![temp](https://user-images.githubusercontent.com/71405368/145714608-7bb30109-c6ac-4c29-8968-a4412307ffd5.png) Design of the front-end part

Sure go ahead 👍
