### ISSUE TITLE
Header and Footer for all pages.

### ISSUE THREAD

**Issue by SuperAayush** [shivshankar9/Student-portal#51]
<img width="1440" alt="Screenshot 2021-12-13 at 5 02 15 PM" src="https://user-images.githubusercontent.com/78820926/145804981-b0574f60-277f-4cf9-aa42-5ac69bbaebd8.png">

**Comment by SuperAayush** [comment]
@shivshankar9  I am thinking to go with an amazing Header and Footer which will be applied to all the pages.
Just suggest to me that either I should continue with the same header that is currently used on the Homepage or make a new one.

**Comment by shivshankar9** [comment]
> @shivshankar9 I am thinking to go with an amazing Header and Footer which will be applied to all the pages. Just suggest to me that either I should continue with the same header that is currently used on the Homepage or make a new one.

Go for it

**Comment by SuperAayush** [comment]
Can you please assign this to me then?

**Comment by shivshankar9** [comment]
> Can you please assign this to me then?

Sure

**Comment by SuperAayush** [comment]
@shivshankar9  Should I PR for any of these headers?
<img width="1440" alt="Screenshot 2021-12-16 at 7 13 23 PM" src="https://user-images.githubusercontent.com/78820926/146383074-dbec77de-2c77-4014-9c67-e74f398ccbe4.png">

<img width="1440" alt="Screenshot 2021-12-16 at 7 12 37 PM" src="https://user-images.githubusercontent.com/78820926/146383069-381a5b67-2959-4680-ae5c-68345804991b.png">

**Comment by SuperAayush** [comment]
I have removed the navbar and created this header all by myself and planning to do the same for the footer. Can you just suggest to me what all should I add or include in footer?

**Comment by Shubhambawner** [comment]
@SuperAayush 
we can just have look at some similer websites's footers, 
having some idea in mind, I would be happy to work with u upon this pr on footer part.

**Comment by SuperAayush** [comment]
@Shubhambawner  Ya go on brother, get yourself assigned as well.

**Comment by aakankshabhende** [comment]
Any updates? @SuperAayush @Shubhambawner

**Comment by SuperAayush** [comment]
@aakankshabhende yes I asked @shivshankar9 above to choose between the two headers but I didn't get a response from his side.
