### ISSUE TITLE
Common html part

### ISSUE THREAD

**Issue by abaran803** [shivshankar9/Student-portal#55]
In all the pages, common HTML parts (like header, footer etc.) are repeated and require to be corrected every time when the common part for the home page is changed. I want to create a different file for that common part and use the reference in all the pages. So that, on changing the common part, we don't need to update all the pages again.

**Comment by abaran803** [comment]
I tried to implement it in my local system a lot of times, and it worked. But it causes a problem with JavaScript. I used "load()" of jQuery and iFrame.
In load(), the part of the HTML is loaded after the loading of the page, but the script work before loading so all the variables storing the old DOM and the function applied do not work on newly generated DOM using load().

**Comment by shivshankar9** [comment]
> I tried to implement it in my local system a lot of times, and it worked. But it causes a problem with JavaScript. I used "load()" of jQuery and iFrame. In load(), the part of the HTML is loaded after the loading of the page, but the script work before loading so all the variables storing the old DOM and the function applied do not work on newly generated DOM using load().

Then

**Comment by Abirpal202049** [comment]
You can implement this using React or Layout Engins like ejs,pug

**Comment by ElyasAmri** [comment]
I agree @Abirpal202049 , but you would need node.js and multiple packages and the project will have to be run as a server rather than be opened as a simple html file. Should that be the case for this project or not, @shivshankar9 ?

**Comment by abaran803** [comment]
We have to change a lot of 

> You can implement this using React or Layout Engins like ejs,pug

I tried fetch API, and it is working properly. We can use it by putting file address in place of url. And it returns promise. We then put the desired js code inside .then() and it will execute after loading the component.
The I don't know using this in all the files is a good approach or not.

**Comment by abaran803** [comment]
> We have to change a lot of
> 
> > You can implement this using React or Layout Engins like ejs,pug
> 
> I tried fetch API, and it is working properly. We can use it by putting file address in place of url. And it returns promise. We then put the desired js code inside .then() and it will execute after loading the component. The I don't know using this in all the files is a good approach or not.

@shivshankar9 Sir, please reply

**Comment by shivshankar9** [comment]
> > We have to change a lot of
> > > You can implement this using React or Layout Engins like ejs,pug
> > 
> > 
> > I tried fetch API, and it is working properly. We can use it by putting file address in place of url. And it returns promise. We then put the desired js code inside .then() and it will execute after loading the component. The I don't know using this in all the files is a good approach or not.
> 
> @shivshankar9 Sir, please reply

Take your time @abaran803  Just try do, if still you face problems then don't forget stackoverflow is always open for you and also you can Just post issue in our group we will try to resolve,

**Comment by abaran803** [comment]
> > > We have to change a lot of
> > > > You can implement this using React or Layout Engins like ejs,pug
> > > 
> > > 
> > > I tried fetch API, and it is working properly. We can use it by putting file address in place of url. And it returns promise. We then put the desired js code inside .then() and it will execute after loading the component. The I don't know using this in all the files is a good approach or not.
> > 
> > 
> > @shivshankar9 Sir, please reply
> 
> Take your time @abaran803 Just try do, if still you face problems then don't forget stackoverflow is always open for you and also you can Just post issue in our group we will try to resolve,

@shivshankar9 Ok, Sir

**Comment by abaran803** [comment]
@shivshankar9 Navbar is not showing due to cross-site access. Fetching navbar from my GitHub repo b/c the absolute path is provided which belong to my repo. I did this b/c I tried it on my repo. Now I want to put the original repo address(i.e. this repo).
