### ISSUE TITLE
Organize The File Structure

### ISSUE THREAD

**Issue by Abirpal202049** [shivshankar9/Student-portal#59]
Put all the css , js under different folders and link then properly and add a .gitignore file also

**Comment by Adit0507** [comment]
May I kindly work on this issue  ? This is my my 1st time doing Open-Source so I will try my best to work on this

**Comment by aakankshabhende** [comment]
Go ahead @Adit0507

**Comment by Adit0507** [comment]
Thank You @aakankshabhende

**Comment by Atif0604** [comment]
Hey @aakankshabhende @Abirpal202049 @shivshankar9 Can i work on this if no one is working on 
as its around 10 days

**Comment by shivshankar9** [comment]
> Hey @aakankshabhende @Abirpal202049 @shivshankar9 Can i work on this if no one is working on as its around 10 days

Yes @Atif0604  go ahead.
