### ISSUE TITLE
Improve the design of the Contact Page

### ISSUE THREAD

**Issue by Adit0507** [shivshankar9/Student-portal#62]
![a](https://user-images.githubusercontent.com/78037846/145992405-c1947c87-664e-40c7-8c99-fd515b85c2c2.PNG)
The design of the Contact page doesn't match the aesthetic of the Home Page, so I want to make the Contact page look a bit more cohesive with the Home Page.

**Comment by Adit0507** [comment]
![aa](https://user-images.githubusercontent.com/78037846/145992844-7afc87a6-8ca1-4f6d-b818-b7f145201b7e.PNG)
 For Reference

**Comment by devikavarshney** [comment]
@shivshankar9 is it done or can I contribute to this one?

**Comment by Adit0507** [comment]
Hi @devikavarshney , I'm currently working on this
