### ISSUE TITLE
No home Button/Navbar  on contact page.

### ISSUE THREAD

**Issue by satyamgupta1495** [shivshankar9/Student-portal#67]
Once landed on the contact page, the user cannot navigate to home or any other section of the page.

![image](https://user-images.githubusercontent.com/51158766/146112601-0880fc97-0aa9-4b93-b2d3-8c85e4cd3591.png)

**Comment by satyamgupta1495** [comment]
Hey @shivshankar9, I wanna work on this issue.

**Comment by shivshankar9** [comment]
> Hey @shivshankar9, I wanna work on this issue.

Yeah sure👍

**Comment by Drish-xD** [comment]
@shivshankar9 Can I work on this?

**Comment by shivshankar9** [comment]
> @shivshankar9 Can I work on this?

This issue Already assigned ,

**Comment by aakankshabhende** [comment]
Any updates? @satyamgupta1495

**Comment by satyamgupta1495** [comment]
already raised a PR. I think its merged could you plz check?
