### ISSUE TITLE
Pdf converter

### ISSUE THREAD

**Issue by shivshankar9** [shivshankar9/Student-portal#7]

**Comment by leesha19** [comment]
do we have to create a pdf converter

**Comment by madhuri878** [comment]
Can you please assign me?

**Comment by leesha19** [comment]
> _No description provided._

hey when i opened the website it shows a file is missing can you please add it

**Comment by shivshankar9** [comment]
> do we have to create a pdf converter

Yes

**Comment by shivshankar9** [comment]
Any updates @leesha19 @madhuri878

**Comment by udith51** [comment]
@shivshankar9 What type of convertor are we expecting here ? Is it something specific like doc-to-pdf or img-to-pdf?

**Comment by shivshankar9** [comment]
> @shivshankar9 What type of convertor are we expecting here ? Is it something specific like doc-to-pdf or img-to-pdf?

***Doc to pdf,***
*Img-to-pdf* already exists

**Comment by udith51** [comment]
Hey @shivshankar9, if this issue thread is inactive, can I work on it?

**Comment by shivshankar9** [comment]
> Hey @shivshankar9, if this issue thread is inactive, can I work on it?

This issue already assigned

> Hey @shivshankar9, if this issue thread is inactive, can I work on it?

Yeah go ahead

**Comment by ssurbhi09** [comment]
What I have to do please explain!

**Comment by shivshankar9** [comment]
> What I have to do please explain!

This issue already assigned @ssurbhi09

**Comment by udith51** [comment]
Hey @shivshankar9, the work is almost done. Our website now takes in a word doc, converts it to pdf and saves it to local system. Should I submit pr and create new issue for styling of the page, because as of now on clicking Word-to-doc it navigates to nowhere.

**Comment by udith51** [comment]
As of now, we have this functionality ready with us.
So maybe after next issue we have design+functionality completed.

**Comment by shivshankar9** [comment]
Just add it in simple way , after that you can create another issue for ui

**Comment by udith51** [comment]
Added pr, please review it and inform if any further changes are required. #84

**Comment by udith51** [comment]
@shivshankar9, you may close this issue. The linked pr has been merged :)
