### ISSUE TITLE
Remove Input Field

### ISSUE THREAD

**Issue by Harshil-Jani** [shivshankar9/Student-portal#72]
![image](https://user-images.githubusercontent.com/79367883/146352113-70dc9f3f-368d-4952-8ff8-a798d52aa4a8.png)

If user creates More Upload sections and then if somehow we want to reduce the created section then We cannot do it. This feature would ease out the process for user to interact rather than re-uploading all the documents.

**Proposed Solution :** Create a button to delete the Form Nodes when clicked.

**Comment by Harshil-Jani** [comment]
I would like to work on this !

**Comment by shivshankar9** [comment]
#65  issue already assigned
