### ISSUE TITLE
Chatbot interface not positioned properly in mobile view

### ISSUE THREAD

**Issue by harshimm** [shivshankar9/Student-portal#73]
Half of the interface is crossing the left margin , due to which the reply words and messages are not visible . And part of it goes behind the navbar.

![Screenshot_2021-12-16-17-07-32-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/87597527/146365219-806d5634-fcb6-4190-abfe-6960ed969a71.jpg)

**Comment by shivshankar9** [comment]
Yes 

> Half of the interface is crossing the left margin , due to which the reply words and messages are not visible . And part of it goes behind the navbar.
> 
> ![Screenshot_2021-12-16-17-07-32-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/87597527/146365219-806d5634-fcb6-4190-abfe-6960ed969a71.jpg)

Yes

**Comment by harshimm** [comment]
Can you assign me this issue as well, Thanks in advance !

**Comment by shivshankar9** [comment]
> Can you assign me this issue as well, Thanks in advance !

Yeah sure go ahead

**Comment by Shubhambawner** [comment]
@shivshankar9 @HarshiniMarappan 
how do we get an issue assigned? do we have to raise it first, or we can be assigned any other also?

**Comment by shivshankar9** [comment]
> @shivshankar9 @HarshiniMarappan how do we get an issue assigned? do we have to raise it first, or we can be assigned any other also?

This issue already assigned,
You can look for other issue which not resolved yet or you can create new issue as well...
