### ISSUE TITLE
Text to PDF button is not functioning

### ISSUE THREAD

**Issue by ARUNBALACHOCKALINGAM** [shivshankar9/Student-portal#74]
![image](https://user-images.githubusercontent.com/53313020/146505612-0849f897-e242-4cc2-a72c-0a23f0524894.png)

**Comment by ARUNBALACHOCKALINGAM** [comment]
I would like to work on this issue

**Comment by devikavarshney** [comment]
@shivshankar9 if no one is working on this issue can I start working on it❓

**Comment by shivshankar9** [comment]
> @shivshankar9 if no one is working on this issue can I start working on it❓

Yes @devikavarshney

**Comment by devikavarshney** [comment]
@shivshankar9 hey can you explain the difference between this issue assigned to me and the #11 issue.

**Comment by shivshankar9** [comment]
Try to resolve this asap,
We will merge first approved PR only,

**Comment by ARUNBALACHOCKALINGAM** [comment]
Working on it

**Comment by devikavarshney** [comment]
@ARUNBALACHOCKALINGAM @shivshankar9 Can we collaborate mine is almost completed have to do some changes.

**Comment by udith51** [comment]
@shivshankar9, this issue was resolved #11
