### ISSUE TITLE
Updating readme.md 

### ISSUE THREAD

**Issue by Korra15** [shivshankar9/Student-portal#8]
Updating the Readme file to elaborate more on the project and why should people contribute to it.

I would like to work on this, could you please assign this to me under SWOC 2.0

**Comment by shivshankar9** [comment]
> Updating the Readme file to elaborate more on the project and why should people contribute to it.
> 
> I would like to work on this, could you please assign this to me under SWOC 2.0

Go ahead

**Comment by Korra15** [comment]
Could you please give me more insights on what exactly is this project and what does it aim to achieve.

**Comment by Korra15** [comment]
> Thank You.
Could you please give me more insights on what exactly is this project and what does it aim to achieve.

**Comment by Korra15** [comment]
Could you please give me more insights on what exactly is this project and what does it aim to achieve.

**Comment by shivshankar9** [comment]
> Could you please give me more insights on what exactly is this project and what does it aim to achieve.

Not everytime possible to open system or find apps for hours
To manage some short task like creating pdf, doc converters, resize documents
And many more things actually we can do it by simply visiting this web app adding all those tool one place to easily accessible,

**Comment by Korra15** [comment]
okay

**Comment by aakankshabhende** [comment]
Any updates? @Korra15

**Comment by ssurbhi09** [comment]
If it is not complete then assign me I can add how to contribute in readme section

**Comment by shivshankar9** [comment]
> If it is not complete then assign me I can add how to contribute in readme section

Yes go ahead

**Comment by ssurbhi09** [comment]
Done @shivshankar9 sir!
