### ISSUE TITLE
Working on Contact Section

### ISSUE THREAD

**Issue by SarandeepSingh17** [shivshankar9/Student-portal#81]
Re-Creating Contact Section matching with HOME-theme and fixing the overlapping of navigation bar
![image](https://user-images.githubusercontent.com/70137752/147203050-75c5ffe4-d96d-422f-bb66-261148d8db21.png)

**Comment by tiasaxena** [comment]
Hey @shivshankar9! Is the issue still open? I can work on redesigning the contact page while making sure it syncs with the home page. Will be happy to help :)

**Comment by aakankshabhende** [comment]
Any updates? @SarandeepSingh17

**Comment by SarandeepSingh17** [comment]
The above issue has been resolved, you can create new issue and work on the responsiveness for the same
