### ISSUE TITLE
About page is missing 😞 and UI design can be improved of the home page as well

### ISSUE THREAD

**Issue by devikavarshney** [shivshankar9/Student-portal#88]
I can **add about page** as well as can improve the all-over **UI design** of the home page keeping in mind the consistency of the home page and about page 😄 @shivshankar9

**Comment by devikavarshney** [comment]
@shivshankar9 Please assign this issue to me and kindly add the SWOC tag as well as the level tag 🙇🏼‍♀️

**Comment by aakankshabhende** [comment]
Any updates? @devikavarshney

**Comment by devikavarshney** [comment]
IN PROGRESS @aakankshabhende

**Comment by shivshankar9** [comment]
> IN PROGRESS @aakankshabhende

??

**Comment by devikavarshney** [comment]
@shivshankar9 sorry for delay I did home page UI but accidentally I made changes in the main branch will you accept it ?

**Comment by devikavarshney** [comment]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/74262916/153561151-ede9dc91-6c20-447f-9d0a-56b89ec9c7d8.png">
<br> <br>
<img width="938" alt="image" src="https://user-images.githubusercontent.com/74262916/153561218-4f2cc29e-52e6-46e7-8c6f-4600ef6609b2.png">
<br> <br>
<img width="960" alt="image" src="https://user-images.githubusercontent.com/74262916/153561296-0858e2b9-7cc5-4d05-8e6b-c03cba46f7f7.png">
<br> <br>
<img width="947" alt="image" src="https://user-images.githubusercontent.com/74262916/153561340-cad3eeb9-c442-40ad-8f12-0df6cec6bcf0.png">
 It looks like this

**Comment by devikavarshney** [comment]
@shivshankar9 have to some more changes can I make another issue for the contact page and other improvements ?

**Comment by devikavarshney** [comment]
Loading -
<br><br>
<img width="952" alt="image" src="https://user-images.githubusercontent.com/74262916/153563246-ec11c2d5-1ad8-45fe-8957-86eb0634171e.png">

**Comment by shivshankar9** [comment]
> @shivshankar9 have to some more changes can I make another issue for the contact page and other improvements ?

Ok

**Comment by devikavarshney** [comment]
@shivshankar9 sorry for delay I did home page UI but accidentally I made changes in the main branch will you accept it ?

**Comment by devikavarshney** [comment]
@shivshankar9 hey Here is one request if you can change the tag from easy to medium as I redesigned the logo too in Figma. And added animations too.

**Comment by devikavarshney** [comment]
@shivshankar9 check this PR #162
